version: "3"

services:
  controller:
    image: reg.rallf.com:8443/galera-controller
    environment:
      - STACK_NAME=${STACK_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.labels.${STACK_NAME}.galera == ${ENV}
      replicas: 1

  node:
    image: reg.rallf.com:8443/galera-node
    command: start
    hostname: {{.Node.Hostname}}
    environment:
      - STACK_NAME=${STACK_NAME}
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.${STACK_NAME}.galera == stage

